stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/earthquake_data_tsunami.csv
      - params.yaml
    params:
      - preprocess.input
      - preprocess.output
      - preprocess.test_size
    outs:
      - data/processed/
    desc: "Preprocess raw earthquake data into training and test sets"

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/
      - params.yaml
      - requirements.txt
    params:
      - train.data_path
      - train.model_path
      - train.n_estimators
      - train.max_depth
    outs:
      - models/model.pkl
    desc: "Train Random Forest model on processed data"

  evaluate:
    cmd: python src/eval.py
    deps:
      - src/eval.py
      - models/model.pkl
      - data/processed/
      - params.yaml
      - requirements.txt
    params:
      - train.data_path
      - train.model_path
    # Removed metrics: - mlruns/ since it's not a local output
    outs:
      - confusion_matrix.png
      - classification_report.json
      - feature_importance.png
    desc: "Evaluate model performance and log metrics"