random_state: 42

preprocess:
  input: data/raw/earthquake_data_tsunami.csv
  output: data/processed/
  test_size: 0.2
  random_state: 42
  

train:
  data_path: data/processed
  model_path: models/model.pkl 
  random_state: 42
  n_estimators: 100
  max_depth: 5

  # Advanced RF parameters
  class_weight: "balanced"        # Handle imbalanced classes
  n_jobs: -1                      # Use all CPU cores
  oob_score: true                 # Out-of-bag validation
  min_samples_split: 2
  min_samples_leaf: 1
  
  # Hyperparameter tuning (optional)
  tune_hyperparams: false
  param_grid:
    n_estimators: [50, 100, 200]
    max_depth: [3, 5, 10, None]
    min_samples_split: [2, 5, 10]
  
evaluate:
  metrics_thresholds:
    f1_min: 0.7
    accuracy_min: 0.75